"""Self-Service Semantic Metric Explorer & Query Builder.

Enables business SMEs, analysts, and operators to slice and dice governed metrics
without writing custom SQL or causing department metric drift.
"""

import streamlit as st
import pandas as pd
from apps.components.data_store import SEMANTIC_METRICS, load_gold_obt_dataset


def render():
    st.markdown("### Self-Service Metric Explorer & Query Studio")
    st.caption("Slice and dice governed business metrics with zero SQL writing and 100% calculation consistency.")

    df_obt = load_gold_obt_dataset()

    col_m, col_d = st.columns(2)
    with col_m:
        chosen_metrics = st.multiselect(
            "Select Governed Metrics:",
            options=list(SEMANTIC_METRICS.keys()),
            default=["total_revenue", "booking_conversion_rate", "average_booking_value"],
            format_func=lambda k: f"{SEMANTIC_METRICS[k]['label']} ({SEMANTIC_METRICS[k]['tier']})"
        )
    with col_d:
        chosen_dims = st.multiselect(
            "Slice by Dimensions:",
            options=["CITY", "PROPERTY_TYPE", "ROOM_TYPE", "PRICE_PER_NIGHT_TAG", "IS_SUPERHOST"],
            default=["CITY", "PROPERTY_TYPE"]
        )

    if not chosen_metrics or not chosen_dims:
        st.info("Please select at least one governed metric and one dimension to compile the query.")
        return

    # Metric Governance Card
    with st.expander("🛡️ Governed Calculation Audit Trail", expanded=False):
        for m in chosen_metrics:
            meta = SEMANTIC_METRICS[m]
            st.markdown(
                f"- **{meta['label']}**: `<code style='color:#FF385C;'>{meta['formula']}</code>` "
                f"— *Accountable Owner: {meta['owner']} | {meta['description']}*"
            )

    # Audited SQL Generator
    compiled_sql = f"""-- Standardized Semantic Query Generated by MetricFlow Engine
SELECT
    {', '.join([f'obt.{d}' for d in chosen_dims])},
    {', '.join([f"{SEMANTIC_METRICS[m]['formula']} AS {m}" for m in chosen_metrics])}
FROM AIRBNB.gold.obt AS obt
GROUP BY {', '.join([f'obt.{d}' for d in chosen_dims])}
ORDER BY 1 ASC;"""

    with st.expander("🔍 Inspect Audited Snowflake SQL (Compiled by Semantic Layer)", expanded=False):
        st.code(compiled_sql, language="sql")

    # Aggregate Data
    res = df_obt.groupby(chosen_dims).apply(
        lambda x: pd.Series({
            "total_revenue": round(x["TOTAL_AMOUNT"].sum(), 2),
            "total_bookings": len(x),
            "booking_conversion_rate": round((x["BOOKING_STATUS"] == "confirmed").mean() * 100, 2),
            "cancellation_rate": round((x["BOOKING_STATUS"] == "cancelled").mean() * 100, 2),
            "average_booking_value": round(x["TOTAL_AMOUNT"].mean(), 2),
            "active_listings_count": x["LISTING_ID"].nunique()
        })
    ).reset_index()

    cols_to_show = chosen_dims + chosen_metrics
    st.markdown('<p class="section-header">Audited Query Results</p>', unsafe_allow_html=True)
    st.dataframe(res[cols_to_show], use_container_width=True)

    c_dl1, _ = st.columns([1, 3])
    with c_dl1:
        st.download_button(
            "📥 Export Governed Results (CSV)",
            data=res[cols_to_show].to_csv(index=False),
            file_name="airbnb_governed_metrics_export.csv",
            mime="text/csv",
            use_container_width=True
        )
